Synstore tool now returns synapse id as output
Sage-Bionetworks-Workflows/dockstore-tool-synapseclient pull request #12
Opened 2019-06-01 14:10 UTC by andrewelamb

2019-06-03 17:28 UTC, kdaily requested changes
Some minor changes but looks good overall! Thank you for writing these!

2019-06-03 17:28 UTC, kdaily commented on synapse-get-annotations-tool.cwl
> +# Authors: Andrew Lamb
please add `dct:creator` tags in the get and set annotations (or schema.org `Person` as in the [CWL user guide](https://www.commonwl.org/user_guide/17-metadata/index.html)).

2019-06-03 17:28 UTC, kdaily commented on synapse-get-annotations-tool.cwl
> +  - id: output_file_name
I know the command line tool provides this, but use `stdout` instead as it's a more standard interface.

2019-06-03 17:28 UTC, kdaily commented on synapse-store-tool.cwl
> +  - id: file_id
Add a comment here to explain the regex and expected output of the `synapse store` command.

2019-06-04 17:44 UTC, kdaily commented on synapse-get-annotations-tool.cwl
> +# Authors: Andrew Lamb
I was having trouble using the old format I had seen in some CWL using `dct:creator`. The schema.org `Person` works for me.

2019-06-05 21:06 UTC, kdaily approved these changes
@andrewelamb add in your [ORCID identifier](https://orcid.org/) when you get one!

2019-06-05 21:06 UTC, kdaily requested changes

2019-06-05 21:06 UTC, kdaily commented on synapse-get-annotations-tool.cwl
> +  edam: http://edamontology.org/
```suggestion
```

You don't use the edam namespace.

2020-06-17 18:09 UTC, thomasyu888 commented on synapse-get-annotations-tool.cwl
> +    dockerPull: sagebionetworks/synapsepythonclient:v1.9.2
```suggestion
    dockerPull: sagebionetworks/synapsepythonclient:v2.1.0
```

2020-06-17 18:10 UTC, thomasyu888 commented on synapse-set-annotations-tool.cwl
> +    dockerPull: sagebionetworks/synapsepythonclient:v1.9.2
```suggestion
    dockerPull: sagebionetworks/synapsepythonclient:v2.1.0
```

2020-06-17 18:13 UTC, thomasyu888 commented on synapse-store-tool.cwl
>    foaf:mbox: "mailto:kenneth.daily@sagebionetworks.org"
```suggestion
s:author:
  - class: s:Person
    s:identifier: https://orcid.org/0000-0001-5729-7376
    s:email: kenneth.daily@sagebionetworks.org
    s:name: Kenneth Daily
```

2020-06-17 18:13 UTC, thomasyu888 commented on synapse-store-tool.cwl
>    foaf: http://xmlns.com/foaf/0.1/
```suggestion
  dct: http://purl.org/dc/terms/
  foaf: http://xmlns.com/foaf/0.1/
```

2020-06-17 18:14 UTC, merged